import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      {
        source: '/:path*',
        has: [{ type: 'host', value: 'yasarunderwear.com' }],
        destination: 'https://www.yasarunderwear.com/:path*',
        permanent: true,
      },
      { source: '/en', destination: '/', permanent: true },
      { source: '/en/', destination: '/', permanent: true },
      { source: '/ru', destination: '/', permanent: true },
      { source: '/ru/', destination: '/', permanent: true },
      { source: '/fr', destination: '/', permanent: true },
      { source: '/fr/', destination: '/', permanent: true },
      { source: '/ar', destination: '/', permanent: true },
      { source: '/ar/', destination: '/', permanent: true },
      { source: '/iletisim', destination: '/contact', permanent: true },
      { source: '/iletisim/', destination: '/contact', permanent: true },
      { source: '/en/contact', destination: '/contact', permanent: true },
      { source: '/en/contact/', destination: '/contact', permanent: true },
      { source: '/en/hakkimizda', destination: '/about/hakkimizda', permanent: true },
      { source: '/en/hakkimizda/', destination: '/about/hakkimizda', permanent: true },
      { source: '/hakkimizda', destination: '/about/hakkimizda', permanent: true },
      { source: '/hakkimizda/', destination: '/about/hakkimizda', permanent: true },
      { source: '/en/vizyon', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/en/vizyon/', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/vizyon', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/vizyon/', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/misyon', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/misyon/', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/ru/vizyon', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/ru/vizyon/', destination: '/about/misyon-vizyon', permanent: true },
      { source: '/en/uretim-tesislerimiz', destination: '/uretim/tesisler', permanent: true },
      { source: '/en/uretim-tesislerimiz/', destination: '/uretim/tesisler', permanent: true },
      { source: '/uretim-tesislerimiz', destination: '/uretim/tesisler', permanent: true },
      { source: '/uretim-tesislerimiz/', destination: '/uretim/tesisler', permanent: true },
      { source: '/kalite-sureclerimiz', destination: '/uretim/kalite-surecleri', permanent: true },
      { source: '/kalite-sureclerimiz/', destination: '/uretim/kalite-surecleri', permanent: true },
      { source: '/en/kalite-sureclerimiz', destination: '/uretim/kalite-surecleri', permanent: true },
      { source: '/en/kalite-sureclerimiz/', destination: '/uretim/kalite-surecleri', permanent: true },
      { source: '/en/erkek-urunleri', destination: '/urunler', permanent: true },
      { source: '/en/erkek-urunleri/', destination: '/urunler', permanent: true },
      { source: '/erkek-urunleri', destination: '/urunler', permanent: true },
      { source: '/erkek-urunleri/', destination: '/urunler', permanent: true },
      { source: '/en/kadin-urunleri', destination: '/urunler', permanent: true },
      { source: '/en/kadin-urunleri/', destination: '/urunler', permanent: true },
      { source: '/kadin-urunleri', destination: '/urunler', permanent: true },
      { source: '/kadin-urunleri/', destination: '/urunler', permanent: true },
      { source: '/en/surdurulebilirlik', destination: '/surdurulebilirlik', permanent: true },
      { source: '/en/surdurulebilirlik/', destination: '/surdurulebilirlik', permanent: true },
      { source: '/sustainability', destination: '/surdurulebilirlik', permanent: true },
      { source: '/sustainability/', destination: '/surdurulebilirlik', permanent: true },
    ];
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 60 * 60 * 24 * 30,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'res.cloudinary.com',
      },
      {
        protocol: 'https',
        hostname: 'weqrfanzkvvlhtoymxdn.supabase.co',
      },
    ],
  },
};

export default nextConfig;
