#!/bin/bash
# Setup production environment variables on Vercel

echo "⚠️  Vercel Dashboard'da aşağıdaki environment variables'ları ekleyin:"
echo ""
echo "Settings → Environment Variables"
echo ""
echo "DATABASE_URL=postgresql://postgres:38Cagatay34@db.weqrfanzkvvlhtoymxdn.supabase.co:5432/postgres?sslmode=require"
echo ""
echo "SUPABASE_URL=https://weqrfanzkvvlhtoymxdn.supabase.co"
echo ""
echo "SUPABASE_SERVICE_KEY=sb_secret_NtYf2mKDzeyI1Hbwd0VKXw_LGESqodL"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=https://weqrfanzkvvlhtoymxdn.supabase.co"
echo ""
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_TEmxUikp0uJyOZ9sLp6Ysw_aoMJTulP"
echo ""
echo "ADMIN_USER=admin"
echo ""
echo "ADMIN_PASS=prod-secret"
echo ""
echo "ADMIN_SECRET=prod-secret"
echo ""
echo "NEXT_PUBLIC_WHATSAPP_NUMBER=+902125190149"
echo ""
echo "NEXT_PUBLIC_WHATSAPP_MESSAGE=Hello I am interested in your products."
